// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************
// fast mode: true
// **************************************************************************
// ignore_for_file: duplicate_import,implementation_imports,library_private_types_in_public_api,multiple_combinators,prefer_const_literals_to_create_immutables,unintended_html_in_doc_comment,unnecessary_import,unused_import,unused_local_variable,unused_shown_name, unnecessary_library_name, unnecessary_library_directive
/// The routeNames auto generated by https://github.com/fluttercandies/ff_annotation_route
const List<String> routeNames = <String>[
  'fluttercandies://aopTestPage',
  'perf://build',
  'perf://frame',
  'perf://image',
  'perf://interaction',
  'perf://phase',
];

/// The routes auto generated by https://github.com/fluttercandies/ff_annotation_route
class Routes {
  const Routes._();

  /// '插桩测试页面'
  ///
  /// [name] : 'fluttercandies://aopTestPage'
  ///
  /// [routeName] : '插桩测试页面'
  static const String fluttercandiesAopTestPage =
      'fluttercandies://aopTestPage';

  /// 'Build 优化演示'
  ///
  /// [name] : 'perf://build'
  ///
  /// [routeName] : 'Build 优化演示'
  ///
  /// [exts] : {'group': 'performance', 'order': '0'}
  static const String perfBuild = 'perf://build';

  /// 'Frame 优化演示'
  ///
  /// [name] : 'perf://frame'
  ///
  /// [routeName] : 'Frame 优化演示'
  ///
  /// [exts] : {'group': 'performance', 'order': '1'}
  static const String perfFrame = 'perf://frame';

  /// 'Image 优化演示'
  ///
  /// [name] : 'perf://image'
  ///
  /// [routeName] : 'Image 优化演示'
  ///
  /// [exts] : {'group': 'performance', 'order': '3'}
  static const String perfImage = 'perf://image';

  /// '点击弹框链路演示'
  ///
  /// [name] : 'perf://interaction'
  ///
  /// [routeName] : '点击弹框链路演示'
  ///
  /// [exts] : {'group': 'interaction', 'order': '0'}
  static const String perfInteraction = 'perf://interaction';

  /// 'Layout/Paint 优化演示'
  ///
  /// [name] : 'perf://phase'
  ///
  /// [routeName] : 'Layout/Paint 优化演示'
  ///
  /// [exts] : {'group': 'performance', 'order': '2'}
  static const String perfPhase = 'perf://phase';
}
