// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************
// fast mode: true
// **************************************************************************
// ignore_for_file: duplicate_import,implementation_imports,library_private_types_in_public_api,multiple_combinators,prefer_const_literals_to_create_immutables,unintended_html_in_doc_comment,unnecessary_import,unused_import,unused_local_variable,unused_shown_name, unnecessary_library_name, unnecessary_library_directive
import 'package:ff_annotation_route_library/ff_annotation_route_library.dart';
import 'package:flutter/widgets.dart';

import 'pages/aop_test_page.dart';
import 'pages/performance/performance_build_page.dart';
import 'pages/performance/performance_frame_page.dart';
import 'pages/performance/performance_image_page.dart';
import 'pages/performance/performance_phase_page.dart';
import 'pages/performance_interaction_page.dart';

/// Get route settings base on route name, auto generated by https://github.com/fluttercandies/ff_annotation_route
FFRouteSettings getRouteSettings({
  required String name,
  Map<String, dynamic>? arguments,
  PageBuilder? notFoundPageBuilder,
}) {
  final Map<String, dynamic> safeArguments =
      arguments ?? const <String, dynamic>{};
  switch (name) {
    case 'fluttercandies://aopTestPage':
      return FFRouteSettings(
        name: name,
        arguments: arguments,
        builder: () => AopTestPage(
          key: asT<Key?>(
            safeArguments['key'],
          ),
        ),
        routeName: '插桩测试页面',
      );
    case 'perf://build':
      return FFRouteSettings(
        name: name,
        arguments: arguments,
        builder: () => PerformanceBuildPage(
          key: asT<Key?>(
            safeArguments['key'],
          ),
        ),
        routeName: 'Build 优化演示',
        exts: <String, dynamic>{
          'group': 'performance',
          'order': '0',
        },
      );
    case 'perf://frame':
      return FFRouteSettings(
        name: name,
        arguments: arguments,
        builder: () => PerformanceFramePage(
          key: asT<Key?>(
            safeArguments['key'],
          ),
        ),
        routeName: 'Frame 优化演示',
        exts: <String, dynamic>{
          'group': 'performance',
          'order': '1',
        },
      );
    case 'perf://image':
      return FFRouteSettings(
        name: name,
        arguments: arguments,
        builder: () => PerformanceImagePage(
          key: asT<Key?>(
            safeArguments['key'],
          ),
        ),
        routeName: 'Image 优化演示',
        exts: <String, dynamic>{
          'group': 'performance',
          'order': '3',
        },
      );
    case 'perf://interaction':
      return FFRouteSettings(
        name: name,
        arguments: arguments,
        builder: () => PerformanceInteractionPage(
          key: asT<Key?>(
            safeArguments['key'],
          ),
        ),
        routeName: '点击弹框链路演示',
        exts: <String, dynamic>{
          'group': 'interaction',
          'order': '0',
        },
      );
    case 'perf://phase':
      return FFRouteSettings(
        name: name,
        arguments: arguments,
        builder: () => PerformancePhasePage(
          key: asT<Key?>(
            safeArguments['key'],
          ),
        ),
        routeName: 'Layout/Paint 优化演示',
        exts: <String, dynamic>{
          'group': 'performance',
          'order': '2',
        },
      );
    default:
      return FFRouteSettings(
        name: FFRoute.notFoundName,
        routeName: FFRoute.notFoundRouteName,
        builder: notFoundPageBuilder ?? () => Container(),
      );
  }
}
