// coverage:ignore-file
// ignore_for_file: constant_identifier_names
//
// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/assets_generator
// **************************************************************************

/// {@template assets_generator.assets_images_40_png.preview}
/// ![](d:\flutter\flutter_aop\beike_aspectd\aop_example\assets\images\40.png)
/// {@endtemplate}

// ignore_for_file: camel_case_types, unused_element, dangling_library_doc_comments, eol_at_end_of_file
class _ {}
