// dart format off
// coverage:ignore-file
// ignore_for_file: constant_identifier_names
//
// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/assets_generator
// **************************************************************************

abstract final class Assets {
  /// {@macro assets_generator.assets_images_40_png.preview}
  static const String assets_images_40_png = 'assets/images/40.png';
}
